// Generated by Mylo Compiler
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

// --- USER IMPORTS ---
#include "vm.h"
#include "mylolib.h"

// --- GENERATED C STRUCTS ---

double __mylo_user_0(double a, double b) {
    return a + b;
    
}

// --- NATIVE WRAPPERS ---
void __wrapper_0(VM* vm) {
    double _raw_b = vm_pop();
    double _raw_a = vm_pop();
double res = __mylo_user_0(_raw_a, _raw_b);
    vm_push(res, T_NUM);
}

// --- STATIC DATA ---
int static_bytecode[] = {17,14,15,0,15,1,30,31,15,2,21,0,0,21,0,1,0,2,20,2,2,22,23,};
int static_lines[] = {1,1,3,3,3,3,5,5,6,6,6,7,7,7,4,4,4,4,4,4,4,4,4,};
double static_constants[] = {0.000000,10.000000,20.000000,};
const char** static_strings = NULL;

// --- MAIN ---
int main() {
    vm_init();
    memcpy(vm.bytecode, static_bytecode, sizeof(static_bytecode));
    memcpy(vm.lines, static_lines, sizeof(static_lines));
    vm.code_size = 23;
    memcpy(vm.constants, static_constants, sizeof(static_constants));
    vm.const_count = 3;
    vm.str_count = 0;
    int std_idx = 0;
    while(std_library[std_idx].name != NULL) { natives[std_idx] = std_library[std_idx].func; std_idx++; }
    natives[std_idx + 0] = __wrapper_0;
    run_vm(false);
    vm_cleanup();
    return 0;
}
