#define MYLO_BINDING_MODE
// Generated by Mylo Compiler
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

// --- USER IMPORTS ---
#include "vm.h"
#include "mylolib.h"

// --- HOST API BRIDGE ---
void (*host_vm_push)(VM*, double, int);
double (*host_vm_pop)(VM*);
int (*host_make_string)(VM*, const char*);
double (*host_heap_alloc)(VM*, int);
double* (*host_vm_resolve_ptr)(VM*, double);
double (*host_vm_store_copy)(VM*, void*, size_t, const char*);
double (*host_vm_store_ptr)(VM*, void*, const char*);
void* (*host_vm_get_ref)(VM*, int, const char*);
void (*host_vm_free_ref)(VM*, int);
NativeFunc* host_natives_array;
#define vm_push (*host_vm_push)
#define vm_pop (*host_vm_pop)
#define make_string (*host_make_string)
#define heap_alloc (*host_heap_alloc)
#define vm_resolve_ptr (*host_vm_resolve_ptr)
#define vm_store_copy (*host_vm_store_copy)
#define vm_store_ptr (*host_vm_store_ptr)
#define vm_get_ref (*host_vm_get_ref)
#define vm_free_ref (*host_vm_free_ref)
#define natives host_natives_array
// --- GENERATED C STRUCTS ---

double __mylo_user_0(VM* vm, double a, double b) {
    return a + b;
    
}

// --- NATIVE WRAPPERS ---
void __wrapper_0(VM* vm) {
    double _raw_b = vm_pop(vm);
    double _raw_a = vm_pop(vm);
double res = __mylo_user_0(vm, _raw_a, _raw_b);
    vm_push(vm, res, T_NUM);
}

#undef make_string
#undef heap_alloc

#ifdef _WIN32
__declspec(dllexport) void mylo_bind_lib(VM* vm, int start_index, MyloAPI* api) {
#else
void mylo_bind_lib(VM* vm, int start_index, MyloAPI* api) {
#endif
    host_vm_push = api->push;
    host_vm_pop = api->pop;
    host_make_string = api->make_string;
    host_heap_alloc = api->heap_alloc;
    host_vm_resolve_ptr = api->resolve_ptr;
    host_vm_store_copy = api->store_copy;
    host_vm_store_ptr = api->store_ptr;
    host_vm_get_ref = api->get_ref;
    host_vm_free_ref = api->free_ref;
    host_natives_array = api->natives_array;
    host_natives_array[start_index + 0] = __wrapper_0;
}
